version: "3.8"
services:
  brain:
    build:
      args:
        NETWORK: mainnet

  web3signer:
    build:
      args:
        NETWORK: mainnet
        PGPASSWORD: mainnet
        POSTGRES_DB: web3signer-mainnet
        POSTGRES_USER: postgres
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 100

  flyway:
    build:
      args:
        NETWORK: mainnet
        PGPASSWORD: mainnet
        POSTGRES_DB: web3signer-mainnet
        POSTGRES_USER: postgres

  postgres:
    build:
      dockerfile: Dockerfile.debian
      args:
        POSTGRES_PASSWORD: mainnet
        PGPASSWORD: mainnet
        POSTGRES_DB: web3signer-mainnet
        POSTGRES_USER: postgres
